### ISSUE TITLE
SQL Server Importer Failure - 

### ISSUE THREAD

**Issue by jelenadreskai** [MauroDataMapper/mdm-core#115]
Hello @olliefreeman, here are details of the bug I found. 

It looks like I am getting a different error from what I reported originally. See below.

Mauro, latest release, SQL importer 5.0.0 version.
Runs on Docker in Windows Server.
On the same Windows Server, there is a SQL server to which I am trying to connect.

Input (3 screens below)
![image](https://user-images.githubusercontent.com/81437684/127071339-c34a8983-29c6-4dfa-99e1-a80830729378.png)
![image](https://user-images.githubusercontent.com/81437684/127071646-3e402121-8c33-402c-9fa4-b45c5d8c7e02.png)
![image](https://user-images.githubusercontent.com/81437684/127071863-cfbe7ff0-5e6d-4af5-a4b2-95d8c48e3c5d.png)

Error in the UI:
![image](https://user-images.githubusercontent.com/81437684/127071964-f375f828-52b4-43de-b444-bd1dde4905fb.png)

Error in Docker console:
![image](https://user-images.githubusercontent.com/81437684/127209214-ec95c46b-b065-46d0-a107-eb713f496b08.png)

However, if I select to Import as New Branch Model Version, and select an existing model, I get the error I sent in the forum. See below:
Error in UI:
![image](https://user-images.githubusercontent.com/81437684/127077782-dd9b4c7a-6f37-4ec4-b164-366e5217ef9b.png)

Error in Docker console:
![image](https://user-images.githubusercontent.com/81437684/127209513-a8703a2e-38bb-4adb-9a03-415df9243f61.png)

I do not know what is the underlying problem, but I guess error messages could be more informative, if possible.

Let me know if you need any further details.

Thanks!

**Comment by olliefreeman** [comment]
So this is actually 2 errors...the stacktrace does NOT relate to the errors during import, this is a separate issue....one which does also need to be looked at.

There appears to be a bug in importing as new documentation version which is whats cuasing the errors you're being shown in the UI.

I will look into both these issues

**Comment by jelenadreskai** [comment]
I've just updated the screenshots. I can get more information for the first issue from the logs.

**Comment by olliefreeman** [comment]
excellent thank you

**Comment by olliefreeman** [comment]
I will add (as an addtl useful piece of info) the concepts around documentation version is that theres no model structure difference between 2 versions but you're trying to import addtl documentation, i.e. descriptions where you have already finalised model.

Realistically this is not ever going to be the case with importing a database as we dont have the ability to import documentation from databases (not that there ever is any)

If you're trying to re-import a previously imported database because there are structural changes (new tables/columns etc) then you should use the "import as new branch model version" option leaving the branch name blank. This will create a new model version which has the concept of "this is the same model as before but with some schema/structure changes"

I would also recommend importing all databases as "finalised" unless you want to add documentation to the model before finalising as you won't be changing the schema/structure of a DataModel for a database inside Mauro, therefore it should be finalised to prevent accidental changes. However you can't add descriptions after finalisation so if you want to add descroptions then you should import as not finalised, add the descriptions then finalise

**Comment by jelenadreskai** [comment]
> I will add (as an addtl useful piece of info) the concepts around documentation version is that theres no model structure difference between 2 versions but you're trying to import addtl documentation, i.e. descriptions where you have already finalised model.
> 
> Realistically this is not ever going to be the case with importing a database as we dont have the ability to import documentation from databases (not that there ever is any)
> 
> If you're trying to re-import a previously imported database because there are structural changes (new tables/columns etc) then you should use the "import as new branch model version" option leaving the branch name blank. This will create a new model version which has the concept of "this is the same model as before but with some schema/structure changes"
> 
> I would also recommend importing all databases as "finalised" unless you want to add documentation to the model before finalising as you won't be changing the schema/structure of a DataModel for a database inside Mauro, therefore it should be finalised to prevent accidental changes. However you can't add descriptions after finalisation so if you want to add descroptions then you should import as not finalised, add the descriptions then finalise

Hi @olliefreeman I am not sure if I follow. I was trying to import the model for the first time. Ideally I want just columns and column type to be imported, and then allow SMEs to add field descriptions. Is this how SQLServerImporter is meant to function?
And I appologize in advance if I am commenting in the wrong place. Did not want to open a new thread on the same topic.
Jelena

**Comment by jimdavies** [comment]
@jelenadreskai @olliefreeman 

> Hi @olliefreeman I am not sure if I follow. I was trying to import the model for the first time. Ideally I want just columns and column type to be imported, and then allow SMEs to add field descriptions. Is this how SQLServerImporter is meant to function?

That's the core use case.   The importer does the work that it can - importing the schema - and then you work on the resulting model to add the information that wasn't there in the database itself - the insights, etc. from the SMEs.

That should just work, and you're probably wondering why Ollie is suggesting finalising on import.  He'll correct me if he had something else in mind, but here's one good reason: you might well go through multiple versions of this model, all with the same schema, **all derived from that same original import**, but with new or revised field descriptions.   

Because the 'asset' (the database) hasn't changed, we refer to these as 'documentation versions'.   The terminology isn't perfect.  What it means is that the new model is intended as a new/updated description of the same asset - the asset itself hasn't changed, there has been no new import or model created from scratch.  

If this is the plan, then it could be useful to finalise the model after import, so you have taken a snapshot of the baseline, and then proceed to create a new 'documentation version' - and further documentation versions as required. 

Note that you wouldn't be repeating the import in creating any of these new versions - the schema is unchanged and (as Ollie says) you're probably not reading in the field descriptions. 

@olliefreeman is this what you were getting at?
