### ISSUE TITLE
Excel Importer missing Model name input box

### ISSUE THREAD

**Issue by jelenadreskai** [MauroDataMapper/mdm-core#124]
**Describe the bug**
User cannot enter Model name, and when import starts it errors out.

**To Reproduce**
1. Go to Data Model Menu
2. Click on 'Import Models'
3. Select Excel File with data to be imported
4. See UI screenshot below - missing Model name
5. If 

**Expected behavior**
User was able to specify a data model name in the past. Now this field is missing. Seems to show up for a milisecond, and then it is removed from the UI.

**Screenshots**
This is a new UI: 
![image](https://user-images.githubusercontent.com/81437684/127531592-6dab266c-f05c-4d5a-937a-de7fd33d0d3c.png)

This is the error message I get when I try to import:
![image](https://user-images.githubusercontent.com/81437684/127532124-2d0afa8f-3100-4fd8-91f9-2c3e4de21fc4.png)

This is my old screen shot of the UI ( a month ago):
![image](https://user-images.githubusercontent.com/81437684/127532331-67189d6e-29f9-4b8a-bfde-37e4b17fea52.png)

**Additional context**
Excel (XLSX) Importer: 4.0.1

**Comment by olliefreeman** [comment]
So the excel importer is not supposed to show the model name box anymore as its actually doesn't allow an override, however the bug is an issue as it shouldn't be throwing an error.

There is supposed to be a fix in releasing 4.0.1 however I just looked at the code and the parameter change in release 4.0.1 has been made the wrong boolean. We will fix this

**Comment by jamesrwelch** [comment]
I'll take the blame for that one... entirely my fault, sorry.
