### ISSUE TITLE
Editor user receives 403 error when editing a Classifier description.

### ISSUE THREAD

**Issue by GBishop-PHSA** [MauroDataMapper/mdm-core#164]
**Describe the bug**
Users in the Editors group are not able to edit a Classifier description, after an Aministrator has added the Editors group to the Classifier.

**To Reproduce**
1. Login as an administrator
2. Select a classifier 
3. Add Edit role to the classifier with rest api call (not available in UI)
	POST http://localhost:8080/api/classifiers/3523b9e7-0450-414c-b827-89e1df0688e7/groupRoles/bba26934-b42a-406e-9538-75800ee61979/userGroups/a9c25617-e7b7-4b3d-ad12-c3e35b18f00d
	Classifier uuid: 3523b9e7-0450-414c-b827-89e1df0688e7
	Group role (Editor) uuid: bba26934-b42a-406e-9538-75800ee61979
	User Group (Editors) uuid: a9c25617-e7b7-4b3d-ad12-c3e35b18f00d
4.  Login as an Editor 
5.  Select the classifier 
6.  Edit the Description and Save through UI (this uses the rest api call):
	PUT http://localhost:8080/api/classifiers/3523b9e7-0450-414c-b827-89e1df0688e7
	{
		id: "3523b9e7-0450-414c-b827-89e1df0688e7",
		description: "New Description"
	}
7. A 403 Unauthorized response is returned and the classifier description is not updated

**Expected behavior**
A 200 response and the description is updated

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 94

**Comment by olliefreeman** [comment]
So the reason this is happening is actually because the permissions model we designed defines the only people who are allowed to edit a container as "container_admin" group role. The editor role and "below" are defined as "model" permissions, however we allow groups with editor level permissions to create containers inside containers they have editor access to so they may create their own content. The container they create will have a new group with the editor as the container admin.

@jamesrwelch has raised the potential of changing our permissions model but we need to sit and think about what we want and how we want it to work.

So at the moment the permissions are actually as designed and this permission level sits on both folders and classifiers.
