### ISSUE TITLE
Pathing API returns incorrect entity on name collision

### ISSUE THREAD

**Issue by Sunspark** [MauroDataMapper/mdm-core#187]
**Describe the bug**
Given a structure as shown here:
![image](https://user-images.githubusercontent.com/5920776/141475873-c30568db-8375-45ce-b065-0acf70efc140.png)
Calling the API with URL:
{{base_url}}/dataModels/path/dm%3Amaurodatamapper%7Cdc%3Aannotation
Returns the JSON snippet shown below, which details the entity at (maurodatamapper > core > annotation):
![image](https://user-images.githubusercontent.com/5920776/141476008-c3434937-6a65-4e96-943f-34e10d283c0d.png)

**To Reproduce**
1. Given a Running Mauro instance
2. Given a data structure where two entities with the same name exist at different levels of the hierachy
3. When I ask the pathing API for a specific entity
4. Then it should return that specific entity
5. ERROR: a different entity that has the same name (but a different path) is returned.

**Expected behavior**
The path API should return the entity described by the path, and 404 if that specific entity does not exist.

**Desktop (please complete the following information):**
 - OS: Win10, Azure VM. Running Mauro in Docker for Windows.
 - Browser: Chrome
 - Version:
     mauro-data-mapper:
        image: 'maurodatamapper/mauro-data-mapper:B4.10.0_F6.6.0'
        build:
            context: mauro-data-mapper
            args:
                MDM_APPLICATION_COMMIT: 4.10.0
                MDM_UI_COMMIT: 6.6.0
                ADDITIONAL_PLUGINS: "uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-database-sqlserver:5.1.0;uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-csv:3.0.0;uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-database-postgresql:4.0.0"
                MDM_UI_THEME_NAME: "default"

**Comment by aaronforshaw** [comment]
In DataClassService we have
```
    @Override
    DataClass findByParentIdAndLabel(UUID parentId, String label) {
        DataClass dataClass = findByDataModelIdAndLabel(parentId, label)
        if (!dataClass) {
            dataClass = DataClass.byParentDataClassId(parentId).eq('label', label).get()
        }
        dataClass
    }
```

```DataClass dataClass = findByDataModelIdAndLabel(parentId, label)``` finds the first of two data classes which match on data model ID and the label 'annotation'. Note that therefore the order in which the annotation classes were added to the data model is significant when reproducing this bug.

Need to change the find so that it restricts to data classes where parent_data_class_id is null.

**Comment by olliefreeman** [comment]
@aaronforshaw I did some major rework to pathing.
I think this issue is cos the DC query is not properly querying the database wrt with or without a parent dataclass.

theres another issue with pathing and folders not finding top level folders and I think it’s because the query is failing when parent.Id is null and I think we should be better written to say “if parent is null then apply the “null parent” query otherwise apply the query which looks at the “parent id equals”
