### ISSUE TITLE
Permissions issue moving versioned folder

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-core#243]
Logged in as an administrator, trying to move a finalised versioned folder from one folder into a sub-folder.  The backend returns: `User does not have the necessary permissions`.

**Comment by olliefreeman** [comment]
You can't move a finalised VF as its considered finalised and therefore uneditable, therefore it doesn't matter who you are. This is def a bug, the folder move needs to ignore the finalisation state

**Comment by olliefreeman** [comment]
@jamesrwelch this is actually because the UI is not using the changeFolder endpoint, its just using the PUT with 
```json
{"id":"23fc4906-c1a9-43fc-8b8f-7414136ff426","parentFolder":"fc6a86e3-2497-4f81-a790-2fc9de387d71"}
```
which isnt allowed as the VF is locked due to finalisation, the same issue will arise for any models if you try to use a standard update to change the folder after the model is finalised.

There is a 2 stage fix to this specific issue:
1. #235 to allow moving a folder to the root
2. a UI fix to use the correct endpoint to change folders and VFs.
